# Octomap server configuration
octomap_frame: world
octomap_resolution: 0.05
max_range: 5.0
sensor_model:
  hit: 0.7
  miss: 0.4
  min: 0.12
  max: 0.97
filter_speckles: true
filter_ground: false
ground_filter/distance: 0.04
ground_filter/angle: 0.15
ground_filter/plane_distance: 0.07
compress_map: true
incremental_2D_projection: false
