sensors:
  - d405_pointcloud
  - d405_depthimage

# PointCloud-based Octomap updater
# Reference: https://moveit.picknik.ai/humble/doc/examples/perception_pipeline/perception_pipeline_tutorial.html
d405_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /d405/depth/color/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.1
  padding_scale: 1.0
  max_update_rate: 1.0
  filtered_cloud_topic: filtered_cloud

# DepthImage-based Octomap updater (alternative method)
d405_depthimage:
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  image_topic: /d405/depth
  queue_size: 5
  near_clipping_plane_distance: 0.16
  far_clipping_plane_distance: 5.0
  shadow_threshold: 0.2
  padding_offset: 0.03
  padding_scale: 4.0
  max_update_rate: 1.0
  filtered_cloud_topic: filtered_cloud